development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
test: &TEST
  adapter: postgresql
  host: localhost
  username: user
  database: app-test

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-prod

cucumber:
  <<: *TEST
