development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: postgres
  password: password
  port: 5454 # Change it to 5432
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: postgres
  password: password
  port: 5454 # Change it to 5432

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: postgres
  password: password
  port: 5454 # Change it to 5432

cucumber:
  <<: *TEST
